"""
Brightdata API service with caching of job IDs and results.
Handles all Brightdata API interactions including request triggering, polling, and result download.

This code is basically fully generated by Open Code.
"""

import hashlib
import json
import os
import pickle
import time
from datetime import datetime, timedelta
from typing import Optional

import requests
from requests import HTTPError
from retry import retry

from util.config import DATA_PARENT_FOLDER, BRIGHTDATA_API_KEY

BRIGHTDATA_BASE_URL = "https://api.brightdata.com"
POLL_INTERVAL_SECONDS = 10
CACHE_DIR = os.path.join(DATA_PARENT_FOLDER, ".brightdata_cache")
JOB_CACHE_FILE = os.path.join(CACHE_DIR, "job_cache.pkl")


def _ensure_cache_dir():
    """Ensure cache directory exists."""
    os.makedirs(CACHE_DIR, exist_ok=True)


def _headers():
    """Return auth headers for Brightdata API."""
    return {
        "Authorization": f"Bearer {BRIGHTDATA_API_KEY}",
        "Content-Type": "application/json",
    }


def _get_cache_key(dataset_id: str, params: dict, body: object) -> str:
    """Generate a cache key from request params and body."""
    cache_data = {
        "dataset_id": dataset_id,
        "params": json.dumps(params, sort_keys=True),
        "body": json.dumps(body, sort_keys=True, default=str),
    }
    cache_str = json.dumps(cache_data, sort_keys=True)
    return hashlib.sha256(cache_str.encode()).hexdigest()


def _load_job_cache() -> dict:
    """Load cached job IDs and their results."""
    _ensure_cache_dir()
    if os.path.exists(JOB_CACHE_FILE):
        try:
            with open(JOB_CACHE_FILE, "rb") as f:
                return pickle.load(f)
        except Exception as e:
            print(f"  Warning: failed to load job cache: {e}")
            return {}
    return {}


def _save_job_cache(cache: dict) -> None:
    """Save job cache to disk."""
    _ensure_cache_dir()
    try:
        with open(JOB_CACHE_FILE, "wb") as f:
            pickle.dump(cache, f)
    except Exception as e:
        print(f"  Warning: failed to save job cache: {e}")


def _get_cached_result(cache_key: str, max_age_hours: int = 168) -> Optional[dict]:
    """
    Retrieve cached result if it exists and is not too old.

    Args:
        cache_key: The cache key for the request
        max_age_hours: Maximum age of cached result in hours (default: 7 days)

    Returns:
        Cached result dict with 'snapshot_id' and 'results', or None if not found/expired
    """
    cache = _load_job_cache()
    if cache_key not in cache:
        return None

    cached_entry = cache[cache_key]
    timestamp = cached_entry.get("timestamp")
    if timestamp is None:
        return None

    age = datetime.now() - datetime.fromisoformat(timestamp)
    if age > timedelta(hours=max_age_hours):
        print(f"  Cache expired for {cache_key[:8]}... (age: {age.days} days)")
        del cache[cache_key]
        _save_job_cache(cache)
        return None

    return cached_entry


def _cache_result(cache_key: str, snapshot_id: str, results: list) -> None:
    """Cache the results of a successful request."""
    cache = _load_job_cache()
    cache[cache_key] = {
        "snapshot_id": snapshot_id,
        "results": results,
        "timestamp": datetime.now().isoformat(),
    }
    _save_job_cache(cache)


@retry(HTTPError, tries=3, delay=2)
def trigger_request(dataset_id: str, params: dict, body: object) -> str:
    """
    Trigger an async Brightdata scraper request.

    Args:
        dataset_id: Brightdata dataset ID
        params: Query parameters dict
        body: Request body (list or dict with input)

    Returns:
        snapshot_id for polling
    """
    url = f"{BRIGHTDATA_BASE_URL}/datasets/v3/trigger"
    resp = requests.post(
        url,
        params={**params, "dataset_id": dataset_id},
        data=json.dumps(body).encode("utf-8"),
        headers=_headers(),
    )

    resp.raise_for_status()
    snapshot_id = resp.json()["snapshot_id"]
    print(f"  Triggered snapshot: {snapshot_id}")
    return snapshot_id


@retry(HTTPError, tries=3, delay=2)
def wait_for_snapshot(snapshot_id: str) -> None:
    """
    Poll until the snapshot status is 'ready'.

    Args:
        snapshot_id: The snapshot ID to poll

    Raises:
        RuntimeError if the snapshot fails
    """
    url = f"{BRIGHTDATA_BASE_URL}/datasets/v3/progress/{snapshot_id}"
    while True:
        resp = requests.get(url, headers=_headers())
        resp.raise_for_status()
        status = resp.json().get("status")
        if status == "ready":
            print(f"  Snapshot {snapshot_id} is ready")
            return
        if status == "failed":
            raise RuntimeError(f"Snapshot {snapshot_id} failed")
        print(
            f"  Snapshot {snapshot_id} status: {status} – waiting {POLL_INTERVAL_SECONDS}s ..."
        )
        time.sleep(POLL_INTERVAL_SECONDS)


@retry(HTTPError, tries=3, delay=2)
def download_snapshot(snapshot_id: str) -> list:
    """
    Download the snapshot results as JSON.

    Args:
        snapshot_id: The snapshot ID to download

    Returns:
        List of result objects
    """
    url = f"{BRIGHTDATA_BASE_URL}/datasets/v3/snapshot/{snapshot_id}"
    resp = requests.get(url, params={"format": "json"}, headers=_headers())
    resp.raise_for_status()
    return resp.json()


def request_with_cache(
        dataset_id: str, params: dict, body: object, cache_max_age_hours: int = 168
) -> list:
    """
    Make a Brightdata API request with caching.

    If a cached result exists and is not too old, returns it without making a new request.
    Otherwise, triggers a new request, polls for completion, downloads results, and caches them.

    Args:
        dataset_id: Brightdata dataset ID
        params: Query parameters dict
        body: Request body
        cache_max_age_hours: Maximum age of cached results in hours

    Returns:
        List of result objects from Brightdata
    """
    cache_key = _get_cache_key(dataset_id, params, body)

    # Check cache first
    cached = _get_cached_result(cache_key, max_age_hours=cache_max_age_hours)
    if cached:
        print(f"  Using cached result for {cache_key[:8]}...")
        return cached["results"]

    # No cache hit - trigger new request
    snapshot_id = trigger_request(dataset_id, params, body)
    wait_for_snapshot(snapshot_id)
    results = download_snapshot(snapshot_id)

    # Cache the results
    _cache_result(cache_key, snapshot_id, results)

    return results


def clear_cache():
    """Clear all cached job results."""
    if os.path.exists(JOB_CACHE_FILE):
        try:
            os.remove(JOB_CACHE_FILE)
            print("  Job cache cleared")
        except Exception as e:
            print(f"  Warning: failed to clear job cache: {e}")


def get_cache_info() -> dict:
    """Get information about current cache."""
    cache = _load_job_cache()
    info = {
        "total_cached_jobs": len(cache),
        "cache_file": JOB_CACHE_FILE,
        "jobs": [],
    }
    for cache_key, entry in cache.items():
        age_hours = (
                            datetime.now() - datetime.fromisoformat(entry["timestamp"])
                    ).total_seconds() / 3600
        info["jobs"].append(
            {
                "cache_key": cache_key[:16] + "...",
                "snapshot_id": entry["snapshot_id"],
                "age_hours": round(age_hours, 2),
                "result_count": len(entry.get("results", [])),
            }
        )
    return info
